// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entitiyframework;

#nullable disable

namespace projectoef.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20221119230341_RestriccionDescripccionFalse")]
    partial class RestriccionDescripccionFalse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("entitiyframework.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("40d79cef-73f1-4fe8-8a6c-168d99e4260a"),
                            Descripcion = "Tareas de trabajo",
                            Nombre = "Trabajo",
                            Peso = 1
                        },
                        new
                        {
                            CategoriaId = new Guid("40d79cef-73f1-4fe8-8a6c-168d99e426bc"),
                            Descripcion = "Tareas personales",
                            Nombre = "Personal",
                            Peso = 2
                        });
                });

            modelBuilder.Entity("entitiyframework.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("40d79cef-73f1-4fe8-8a6c-168d99e4260b"),
                            CategoriaId = new Guid("40d79cef-73f1-4fe8-8a6c-168d99e4260a"),
                            Descripcion = "Tarea 1 de trabajo",
                            FechaCreacion = new DateTime(2022, 11, 19, 20, 3, 41, 382, DateTimeKind.Local).AddTicks(466),
                            PrioridadTarea = 0,
                            Titulo = "Tarea 1"
                        },
                        new
                        {
                            TareaId = new Guid("40d79cef-73f1-4fe8-8a6c-168d99e4260c"),
                            CategoriaId = new Guid("40d79cef-73f1-4fe8-8a6c-168d99e426bc"),
                            Descripcion = "Tarea 2 personal",
                            FechaCreacion = new DateTime(2022, 11, 19, 20, 3, 41, 382, DateTimeKind.Local).AddTicks(480),
                            PrioridadTarea = 1,
                            Titulo = "Tarea 2"
                        });
                });

            modelBuilder.Entity("entitiyframework.Models.Tarea", b =>
                {
                    b.HasOne("entitiyframework.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tarea_Categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("entitiyframework.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
